update `wgpu` to `0.13`
iced-rs/iced pull request #1378
Opened 2022-07-02 07:41 UTC by Cupnfish

2022-07-02 07:58 UTC, Cupnfish commented on wgpu/Cargo.toml
> +wgpu_glyph = { version = "0.16", git = "https://github.com/Cupnfish/wgpu_glyph.git", branch = "wgpu-0.13" }
Waiting to merge this: https://github.com/hecrj/wgpu_glyph/pull/89

2022-07-02 11:32 UTC, hecrj commented on wgpu/Cargo.toml
> +webgl = [ "wgpu/webgl" ]
Can we remove these formatting changes?

2022-07-02 11:34 UTC, hecrj commented on examples/integration_wgpu/src/main.rs
> -                        local_pool.run_until_stalled();
No more local pool! That's great 😄

2022-07-02 14:12 UTC, PolyMeilex requested changes

2022-07-02 14:12 UTC, PolyMeilex commented on wgpu/src/shader/image.wgsl
>  };
This has to be updated to new syntax

2022-07-02 14:37 UTC, PolyMeilex commented
Also, `;` after struct defs is no longer needed (rust like syntax), but that's just a purely stylistic choice. I'm just noting that switching to that syntax is now possible.

2022-07-03 13:51 UTC, hecrj approved these changes
I made some small changes here and there, but everything looks great! Thanks for taking care of this so quickly :bow:

Also very glad to see all of the `wgpu` improvements! :tada:

2022-07-03 15:34 UTC, PolyMeilex approved these changes
No more comments from me, looks good to me as well.

2022-07-03 15:35 UTC, merged