Remove Application::title() and replace it with an action.
iced-rs/iced pull request #1671
Opened 2023-01-24 16:41 UTC by thunderstorm010

Needs review (I probably don't know what I'm doing)

Removes the method `Application::title()`.
Introduces a new field in `Settings`: `title: String`
Introduces a new action: `action::Title(String)`

**This is a breaking change.**

2023-01-24 18:49 UTC, hecrj requested changes
Thanks for giving this a shot!

I have some suggestions. Let me know!

2023-01-24 18:49 UTC, hecrj commented on glutin/src/application.rs
> +            &settings.window.title,
Since the `title` is in the `settings.window` already, we can just remove the argument here and access it directly in `into_builder`.

2023-01-24 18:49 UTC, hecrj commented on native/src/window/action.rs
> +    Title(String)
Let's call it `ChangeTitle`.

2023-01-24 18:49 UTC, hecrj commented on src/window/settings.rs
> +            title: String::from("Iced")
Maybe something like "A cool application" would be _cooler_.

2023-01-24 18:49 UTC, hecrj commented on winit/src/application/state.rs
> +
Unnecessary blank line here :)

2023-01-24 18:49 UTC, hecrj commented on winit/src/application/state.rs
Same here. We can delete this blank line.

2023-01-24 18:49 UTC, hecrj commented on winit/src/settings.rs
> +    /// Title of the window.
```suggestion
    /// The title of the window.
```

For consistency.

2023-01-25 07:28 UTC, thunderstorm010 reviewed
There's some formatting changes done by `cargo fmt`. Are those okay?

2023-02-10 19:15 UTC, hecrj commented
Closing as discussed on Discord:

> After some thought while changing the examples... I am not sure this is a good change.
> The title of an application is normally inherently related to a bunch of application state. Therefore, using a Command to update it seems inappropriate since you will have to potentially couple this state in many different parts of your update logic.
> Some examples become more complex, so I don't see a net gain here.

2023-02-10 19:15 UTC, closed without merging