Upgrade `palette` dependency
iced-rs/iced pull request #1875
Opened 2023-05-25 20:14 UTC by clarkmoody

- Upgrades `palette` to 0.7 across the library
- Fixes breakages
  - Use `rgb::Rgb` instead of `Srgb` directly
  - `RelativeContrast` trait has been deprecated in favor of `color_difference::Wcag21RelativeContrast`
  - `Hue::to_positive_degrees()` -> `Hue::into_positive_degrees()`

2023-05-25 20:58 UTC, hecrj requested changes

2023-05-25 20:58 UTC, hecrj commented on core/src/color.rs
> +        Color::new(rgba.red, rgba.green, rgba.blue, rgba.alpha)
Why has this been changed? `Color` is in the sRGB color space.

2023-05-25 21:43 UTC, hecrj commented
Thanks! Not sure what's up with CI. Let me take a look.

2023-05-25 21:52 UTC, hecrj commented on core/src/color.rs
> +        Color::new(rgba.red, rgba.green, rgba.blue, rgba.alpha)
Ah, I see. It's a type definition! Still, it seems more descriptive to use `Srgb` directly.

2023-05-25 22:08 UTC, hecrj commented on core/src/color.rs
> +        Color::new(rgba.red, rgba.green, rgba.blue, rgba.alpha)
Reverted it in b741893013eda90045e5a3950c37ba21d073b351 for now.

2023-05-25 22:32 UTC, hecrj approved these changes
Looks good to me! Let me know if you agree with the `Srgb` change.

2023-05-26 16:21 UTC, clarkmoody commented
Sticking with `Srgb` is fine with me :shipit:

2023-05-26 17:02 UTC, merged