add helper fun
iced-rs/iced pull request #2260
Opened 2024-02-18 15:57 UTC by wiiznokes

This add some new method to the Padding struct. 

I have some other ideas, like also provide some more method like

```rust 
/// Create a [`Padding`] with equally spaces of the right and left side
    pub fn vertical(padding: f32) -> Self {
        Self {
            left: padding,
            right: padding,
            ..Padding::ZERO
        }
    }
```
and the same for vertical, but that will involve breaking change.

And also provide a constructor API alternative:

```rust 
pub fn vertical(self, padding: f32) -> Self {
        self.left = padding;
        self.right = padding;
        self
    }
```

to allow writting this:

```rust 
let padding = Padding::horizontal(10f32)
            .bottom(5f32);
```

But this will involve, reanaming the method i written like such

```rust 
fn new_top()
fn new_bottom()
fn new_vertical()
```

which is fine imo.

I think it make more sense to provide this funcions rather than

```rust
pub fn vertical(self) -> f32 {
        self.top + self.bottom
    }
```

because i don't really see a lot of use case for this (user perspective).

2024-02-19 07:39 UTC, hecrj requested changes

2024-02-19 07:39 UTC, hecrj commented on core/src/padding.rs
> +    /// Create a top Padding
Let's use the link notation and end with a period:

```rust
/// Create a top [`Padding`].
```

2024-02-19 10:41 UTC, Koranir commented
I think that instead of these new function being constructors, they should be builder-like functions. It makes the api a lot more flexible, at the small cost of turning `Padding::bottom(5.0)` into `Padding::ZERO.bottom(5.0)`.

2024-02-19 10:43 UTC, Koranir commented
E.g.
```rust
    /// Sets the top padding to `padding`.
    pub const fn top(self, padding: f32) -> Self {
        Self {
            top: padding,
            ..self
        }
    }
```

2024-02-19 16:41 UTC, wiiznokes commented
> I think that instead of these new function being constructors, they should be builder-like functions. It makes the api a lot more flexible, at the small cost of turning Padding::bottom(5.0) into Padding::ZERO.bottom(5.0).

Yes that what i was saying. But we can still use `Padding::new_bottom(5.0)` for constructor and `padding.bottom(5.0)` for builder.

What do you think @hecrj ?

2024-02-19 22:06 UTC, Koranir commented
> > I think that instead of these new function being constructors, they should be builder-like functions. It makes the api a lot more flexible, at the small cost of turning Padding::bottom(5.0) into Padding::ZERO.bottom(5.0).
> 
> Yes that what i was saying. But we can still use `Padding::new_bottom(5.0)` for constructor and `padding.bottom(5.0)` for builder.
> 
> What do you think @hecrj ?

The naming convention for constructors of this type is `with_<thing>`, so `Padding::with_bottom(5.0)` in this example. However, I don't think having separate constructors for each is required here and just adds unnecessary complexity.

2024-02-19 23:13 UTC, wiiznokes commented
> However, I don't think having separate constructors for each is required here and just adds unnecessary complexity.

I better than

```rust
Padding {
   bottom: 5.0,
   ..Padding::ZERO
}
```
(one line instead of four)

2024-02-20 00:38 UTC, Koranir commented
> > However, I don't think having separate constructors for each is required here and just adds unnecessary complexity.
> 
> I better than
> 
> ```rust
> Padding {
>    bottom: 5.0,
>    ..Padding::ZERO
> }
> ```
> 
> (one line instead of four)

With builder pattern it would be
```rust
Padding::ZERO.bottom(5.0)
```

2024-02-23 22:27 UTC, wiiznokes commented
> With builder pattern it would be
> 
> ```rust
> Padding::ZERO.bottom(5.0)
> ```

True, still prefer the `with_bottom` though.

2024-02-23 22:38 UTC, wiiznokes commented
we could also add `with_vertical`, `with_horizontal` and change the behavior of `vertical` and `horizontal`.

2024-02-23 22:44 UTC, wiiznokes commented
I think we could also remove the From impl

2024-07-12 19:40 UTC, closed without merging